"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.edit_throttle import EditThrottle
globals()['EditThrottle'] = EditThrottle
from greenlake_data_services.model.edit_system_parameters import EditSystemParameters


class TestEditSystemParameters(unittest.TestCase):
    """EditSystemParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditSystemParameters(self):
        """Test EditSystemParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditSystemParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
