"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.associated_links import AssociatedLinks
from greenlake_data_services.model.nimble_folder_details import NimbleFolderDetails
from greenlake_data_services.model.nimble_folder_fields_with_sort_key import NimbleFolderFieldsWithSortKey
from greenlake_data_services.model.nimble_volume_summary import NimbleVolumeSummary
globals()['AssociatedLinks'] = AssociatedLinks
globals()['NimbleFolderDetails'] = NimbleFolderDetails
globals()['NimbleFolderFieldsWithSortKey'] = NimbleFolderFieldsWithSortKey
globals()['NimbleVolumeSummary'] = NimbleVolumeSummary
from greenlake_data_services.model.nimble_folder_list_items_inner import NimbleFolderListItemsInner


class TestNimbleFolderListItemsInner(unittest.TestCase):
    """NimbleFolderListItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleFolderListItemsInner(self):
        """Test NimbleFolderListItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleFolderListItemsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
