"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.remote_copy_link_port_position import RemoteCopyLinkPortPosition
globals()['RemoteCopyLinkPortPosition'] = RemoteCopyLinkPortPosition
from greenlake_data_services.model.remote_copy_link import RemoteCopyLink


class TestRemoteCopyLink(unittest.TestCase):
    """RemoteCopyLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteCopyLink(self):
        """Test RemoteCopyLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoteCopyLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
