"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.volume_set_host_group_list import VolumeSetHostGroupList
globals()['VolumeSetHostGroupList'] = VolumeSetHostGroupList
from greenlake_data_services.model.volume_set_proximity_settings import VolumeSetProximitySettings


class TestVolumeSetProximitySettings(unittest.TestCase):
    """VolumeSetProximitySettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVolumeSetProximitySettings(self):
        """Test VolumeSetProximitySettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VolumeSetProximitySettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
