"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.state import STATE
globals()['STATE'] = STATE
from greenlake_data_services.model.enclosure_disk_loop import EnclosureDiskLoop


class TestEnclosureDiskLoop(unittest.TestCase):
    """EnclosureDiskLoop unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnclosureDiskLoop(self):
        """Test EnclosureDiskLoop"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnclosureDiskLoop()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
