# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import greenlake-data-services
from greenlake-data-services.models.create_host_group_input import CreateHostGroupInput  # noqa: E501
from greenlake-data-services.rest import ApiException


class TestCreateHostGroupInput(unittest.TestCase):
    """CreateHostGroupInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateHostGroupInput(self):
        """Test CreateHostGroupInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = greenlake-data-services.models.create_host_group_input.CreateHostGroupInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
