"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.capacity_series_data import CapacitySeriesData


class TestCapacitySeriesData(unittest.TestCase):
    """CapacitySeriesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCapacitySeriesData(self):
        """Test CapacitySeriesData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CapacitySeriesData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
