# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import greenlake-data-services
from greenlake-data-services.models.replication_partner_list_policies import ReplicationPartnerListPolicies  # noqa: E501
from greenlake-data-services.rest import ApiException


class TestReplicationPartnerListPolicies(unittest.TestCase):
    """ReplicationPartnerListPolicies unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReplicationPartnerListPolicies(self):
        """Test ReplicationPartnerListPolicies"""
        # FIXME: construct object with mandatory attributes with example values
        # model = greenlake-data-services.models.replication_partner_list_policies.ReplicationPartnerListPolicies()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
