"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.associated_links_inner import AssociatedLinksInner
globals()['AssociatedLinksInner'] = AssociatedLinksInner
from greenlake_data_services.model.ee_associated_links import EeAssociatedLinks


class TestEeAssociatedLinks(unittest.TestCase):
    """EeAssociatedLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEeAssociatedLinks(self):
        """Test EeAssociatedLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EeAssociatedLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
