"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.app_key_value import AppKeyValue
from greenlake_data_services.model.common_fields import CommonFields
from greenlake_data_services.model.fields_without_filter import FieldsWithoutFilter
globals()['AppKeyValue'] = AppKeyValue
globals()['CommonFields'] = CommonFields
globals()['FieldsWithoutFilter'] = FieldsWithoutFilter
from greenlake_data_services.model.application_server_details import ApplicationServerDetails


class TestApplicationServerDetails(unittest.TestCase):
    """ApplicationServerDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationServerDetails(self):
        """Test ApplicationServerDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationServerDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
