"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimble_changes import NimbleChanges
globals()['NimbleChanges'] = NimbleChanges
from greenlake_data_services.model.nimble_initiator_review import NimbleInitiatorReview


class TestNimbleInitiatorReview(unittest.TestCase):
    """NimbleInitiatorReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleInitiatorReview(self):
        """Test NimbleInitiatorReview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleInitiatorReview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
