"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimble_volume_filterable_fields_without_filter import NimbleVolumeFilterableFieldsWithoutFilter


class TestNimbleVolumeFilterableFieldsWithoutFilter(unittest.TestCase):
    """NimbleVolumeFilterableFieldsWithoutFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleVolumeFilterableFieldsWithoutFilter(self):
        """Test NimbleVolumeFilterableFieldsWithoutFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleVolumeFilterableFieldsWithoutFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
