"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.manufacturing_single import ManufacturingSingle
from greenlake_data_services.model.primera_application_set_capacity_stats_associated_links import PrimeraApplicationSetCapacityStatsAssociatedLinks
globals()['ManufacturingSingle'] = ManufacturingSingle
globals()['PrimeraApplicationSetCapacityStatsAssociatedLinks'] = PrimeraApplicationSetCapacityStatsAssociatedLinks
from greenlake_data_services.model.node_memory_details import NodeMemoryDetails


class TestNodeMemoryDetails(unittest.TestCase):
    """NodeMemoryDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeMemoryDetails(self):
        """Test NodeMemoryDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeMemoryDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
