# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import greenlake-data-services
from greenlake-data-services.models.snapshot_from_volume import SnapshotFromVolume  # noqa: E501
from greenlake-data-services.rest import ApiException


class TestSnapshotFromVolume(unittest.TestCase):
    """SnapshotFromVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotFromVolume(self):
        """Test SnapshotFromVolume"""
        # FIXME: construct object with mandatory attributes with example values
        # model = greenlake-data-services.models.snapshot_from_volume.SnapshotFromVolume()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
