"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.remote_copy_link import RemoteCopyLink
globals()['RemoteCopyLink'] = RemoteCopyLink
from greenlake_data_services.model.remote_copy_links import RemoteCopyLinks


class TestRemoteCopyLinks(unittest.TestCase):
    """RemoteCopyLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteCopyLinks(self):
        """Test RemoteCopyLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoteCopyLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
