"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.disk_filterable_fields import DiskFilterableFields


class TestDiskFilterableFields(unittest.TestCase):
    """DiskFilterableFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiskFilterableFields(self):
        """Test DiskFilterableFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DiskFilterableFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
