"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimble_storage_system_summary_list_items_inner import NimbleStorageSystemSummaryListItemsInner
globals()['NimbleStorageSystemSummaryListItemsInner'] = NimbleStorageSystemSummaryListItemsInner
from greenlake_data_services.model.nimble_storage_system_summary_list import NimbleStorageSystemSummaryList


class TestNimbleStorageSystemSummaryList(unittest.TestCase):
    """NimbleStorageSystemSummaryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleStorageSystemSummaryList(self):
        """Test NimbleStorageSystemSummaryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleStorageSystemSummaryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
