"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.ee_associated_links import EeAssociatedLinks
globals()['EeAssociatedLinks'] = EeAssociatedLinks
from greenlake_data_services.model.enclosure_expander_details import EnclosureExpanderDetails


class TestEnclosureExpanderDetails(unittest.TestCase):
    """EnclosureExpanderDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnclosureExpanderDetails(self):
        """Test EnclosureExpanderDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnclosureExpanderDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
