"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.service_ports import ServicePorts


class TestServicePorts(unittest.TestCase):
    """ServicePorts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServicePorts(self):
        """Test ServicePorts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServicePorts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
