"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.associated_links import AssociatedLinks
from greenlake_data_services.model.nimble_controller_details import NimbleControllerDetails
from greenlake_data_services.model.nimble_controller_fields_with_sort_key import NimbleControllerFieldsWithSortKey
from greenlake_data_services.model.nimble_ns_ctrlr_hw_sensor_info import NimbleNsCtrlrHwSensorInfo
from greenlake_data_services.model.nimble_ns_ctrlr_nvme_card import NimbleNsCtrlrNvmeCard
from greenlake_data_services.model.nimble_ns_ctrlr_raid_info import NimbleNsCtrlrRaidInfo
globals()['AssociatedLinks'] = AssociatedLinks
globals()['NimbleControllerDetails'] = NimbleControllerDetails
globals()['NimbleControllerFieldsWithSortKey'] = NimbleControllerFieldsWithSortKey
globals()['NimbleNsCtrlrHwSensorInfo'] = NimbleNsCtrlrHwSensorInfo
globals()['NimbleNsCtrlrNvmeCard'] = NimbleNsCtrlrNvmeCard
globals()['NimbleNsCtrlrRaidInfo'] = NimbleNsCtrlrRaidInfo
from greenlake_data_services.model.nimble_controller_list_items_inner import NimbleControllerListItemsInner


class TestNimbleControllerListItemsInner(unittest.TestCase):
    """NimbleControllerListItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleControllerListItemsInner(self):
        """Test NimbleControllerListItemsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleControllerListItemsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
