# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import greenlake-data-services
from greenlake-data-services.models.nimble_network_interface_list import NimbleNetworkInterfaceList  # noqa: E501
from greenlake-data-services.rest import ApiException


class TestNimbleNetworkInterfaceList(unittest.TestCase):
    """NimbleNetworkInterfaceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleNetworkInterfaceList(self):
        """Test NimbleNetworkInterfaceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = greenlake-data-services.models.nimble_network_interface_list.NimbleNetworkInterfaceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
