"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.maintenance_mode_inner_end_time import MaintenanceModeInnerEndTime


class TestMaintenanceModeInnerEndTime(unittest.TestCase):
    """MaintenanceModeInnerEndTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaintenanceModeInnerEndTime(self):
        """Test MaintenanceModeInnerEndTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MaintenanceModeInnerEndTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
