"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.calendar import Calendar
from greenlake_data_services.model.policy import Policy
from greenlake_data_services.model.primera_application_set_details_initiators_inner import PrimeraApplicationSetDetailsInitiatorsInner
from greenlake_data_services.model.primera_volume_details_associated_links_inner import PrimeraVolumeDetailsAssociatedLinksInner
from greenlake_data_services.model.snapshot_tdvvsize import SnapshotTdvvsize
from greenlake_data_services.model.space import Space
from greenlake_data_services.model.state import STATE
from greenlake_data_services.model.user_allocation_settings_single import UserAllocationSettingsSingle
from greenlake_data_services.model.volume_performance import VolumePerformance
globals()['Calendar'] = Calendar
globals()['Policy'] = Policy
globals()['PrimeraApplicationSetDetailsInitiatorsInner'] = PrimeraApplicationSetDetailsInitiatorsInner
globals()['PrimeraVolumeDetailsAssociatedLinksInner'] = PrimeraVolumeDetailsAssociatedLinksInner
globals()['STATE'] = STATE
globals()['SnapshotTdvvsize'] = SnapshotTdvvsize
globals()['Space'] = Space
globals()['UserAllocationSettingsSingle'] = UserAllocationSettingsSingle
globals()['VolumePerformance'] = VolumePerformance
from greenlake_data_services.model.primera_volume_details import PrimeraVolumeDetails


class TestPrimeraVolumeDetails(unittest.TestCase):
    """PrimeraVolumeDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrimeraVolumeDetails(self):
        """Test PrimeraVolumeDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PrimeraVolumeDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
