"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nw_cim_edit_cim import NwCimEditCim


class TestNwCimEditCim(unittest.TestCase):
    """NwCimEditCim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNwCimEditCim(self):
        """Test NwCimEditCim"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NwCimEditCim()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
