"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.enclosure_disk_list import EnclosureDiskList
globals()['EnclosureDiskList'] = EnclosureDiskList
from greenlake_data_services.model.enclosure_disks_summary_list import EnclosureDisksSummaryList


class TestEnclosureDisksSummaryList(unittest.TestCase):
    """EnclosureDisksSummaryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnclosureDisksSummaryList(self):
        """Test EnclosureDisksSummaryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnclosureDisksSummaryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
