"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimble_array import NimbleArray
globals()['NimbleArray'] = NimbleArray
from greenlake_data_services.model.nimble_array_list import NimbleArrayList


class TestNimbleArrayList(unittest.TestCase):
    """NimbleArrayList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleArrayList(self):
        """Test NimbleArrayList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleArrayList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
