"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.allocation import Allocation
from greenlake_data_services.model.cpg_alert import CpgAlert
from greenlake_data_services.model.cpg_grow import CpgGrow
from greenlake_data_services.model.primera_pool_details_dedup_version import PrimeraPoolDetailsDedupVersion
from greenlake_data_services.model.snap_space import SnapSpace
from greenlake_data_services.model.state import State
globals()['Allocation'] = Allocation
globals()['CpgAlert'] = CpgAlert
globals()['CpgGrow'] = CpgGrow
globals()['PrimeraPoolDetailsDedupVersion'] = PrimeraPoolDetailsDedupVersion
globals()['SnapSpace'] = SnapSpace
globals()['State'] = State
from greenlake_data_services.model.primera_pool_list import PrimeraPoolList


class TestPrimeraPoolList(unittest.TestCase):
    """PrimeraPoolList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrimeraPoolList(self):
        """Test PrimeraPoolList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PrimeraPoolList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
