"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.kpi_metrics import KpiMetrics
globals()['KpiMetrics'] = KpiMetrics
from greenlake_data_services.model.volume_performance import VolumePerformance


class TestVolumePerformance(unittest.TestCase):
    """VolumePerformance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVolumePerformance(self):
        """Test VolumePerformance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VolumePerformance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
