"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.led import LED
from greenlake_data_services.model.manufacturing_single import ManufacturingSingle
from greenlake_data_services.model.primera_application_set_capacity_stats_associated_links import PrimeraApplicationSetCapacityStatsAssociatedLinks
from greenlake_data_services.model.state import STATE
globals()['LED'] = LED
globals()['ManufacturingSingle'] = ManufacturingSingle
globals()['PrimeraApplicationSetCapacityStatsAssociatedLinks'] = PrimeraApplicationSetCapacityStatsAssociatedLinks
globals()['STATE'] = STATE
from greenlake_data_services.model.node_power_supply_details import NodePowerSupplyDetails


class TestNodePowerSupplyDetails(unittest.TestCase):
    """NodePowerSupplyDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodePowerSupplyDetails(self):
        """Test NodePowerSupplyDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodePowerSupplyDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
