"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.associated_links import AssociatedLinks
from greenlake_data_services.model.nimble_access_control_record_details import NimbleAccessControlRecordDetails
from greenlake_data_services.model.nimble_access_control_record_fields_without_sort_key import NimbleAccessControlRecordFieldsWithoutSortKey
from greenlake_data_services.model.nimble_ns_snap_lun_info import NimbleNsSnapLunInfo
globals()['AssociatedLinks'] = AssociatedLinks
globals()['NimbleAccessControlRecordDetails'] = NimbleAccessControlRecordDetails
globals()['NimbleAccessControlRecordFieldsWithoutSortKey'] = NimbleAccessControlRecordFieldsWithoutSortKey
globals()['NimbleNsSnapLunInfo'] = NimbleNsSnapLunInfo
from greenlake_data_services.model.nimble_access_control_record_details_with_request_uri import NimbleAccessControlRecordDetailsWithRequestUri


class TestNimbleAccessControlRecordDetailsWithRequestUri(unittest.TestCase):
    """NimbleAccessControlRecordDetailsWithRequestUri unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleAccessControlRecordDetailsWithRequestUri(self):
        """Test NimbleAccessControlRecordDetailsWithRequestUri"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleAccessControlRecordDetailsWithRequestUri()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
