"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.protection_template_action import ProtectionTemplateAction
globals()['ProtectionTemplateAction'] = ProtectionTemplateAction
from greenlake_data_services.model.remove_protection_templates import RemoveProtectionTemplates


class TestRemoveProtectionTemplates(unittest.TestCase):
    """RemoveProtectionTemplates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoveProtectionTemplates(self):
        """Test RemoveProtectionTemplates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoveProtectionTemplates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
