"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimble_ports_list_fibre_channel_interface_items_inner import NimblePortsListFibreChannelInterfaceItemsInner
globals()['NimblePortsListFibreChannelInterfaceItemsInner'] = NimblePortsListFibreChannelInterfaceItemsInner
from greenlake_data_services.model.nimble_ports_list_fibre_channel_interface import NimblePortsListFibreChannelInterface


class TestNimblePortsListFibreChannelInterface(unittest.TestCase):
    """NimblePortsListFibreChannelInterface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimblePortsListFibreChannelInterface(self):
        """Test NimblePortsListFibreChannelInterface"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimblePortsListFibreChannelInterface()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
