"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.tx_fault_pin import TxFaultPin


class TestTxFaultPin(unittest.TestCase):
    """TxFaultPin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxFaultPin(self):
        """Test TxFaultPin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TxFaultPin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
