"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimble_space_domain_fields_without_sort_key import NimbleSpaceDomainFieldsWithoutSortKey


class TestNimbleSpaceDomainFieldsWithoutSortKey(unittest.TestCase):
    """NimbleSpaceDomainFieldsWithoutSortKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleSpaceDomainFieldsWithoutSortKey(self):
        """Test NimbleSpaceDomainFieldsWithoutSortKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleSpaceDomainFieldsWithoutSortKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
