"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.led import LED
globals()['LED'] = LED
from greenlake_data_services.model.ec_dc4data import EcDc4data


class TestEcDc4data(unittest.TestCase):
    """EcDc4data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcDc4data(self):
        """Test EcDc4data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EcDc4data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
