"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.error_response import ErrorResponse
globals()['ErrorResponse'] = ErrorResponse
from greenlake_data_services.model.tasks_bad_request import TasksBadRequest


class TestTasksBadRequest(unittest.TestCase):
    """TasksBadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTasksBadRequest(self):
        """Test TasksBadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TasksBadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
