"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.admit_time import AdmitTime
from greenlake_data_services.model.disk_associated_links import DiskAssociatedLinks
from greenlake_data_services.model.disk_capacity import DiskCapacity
from greenlake_data_services.model.disk_loop import DiskLoop
from greenlake_data_services.model.disk_position import DiskPosition
from greenlake_data_services.model.disk_position_now import DiskPositionNow
from greenlake_data_services.model.error_count import ErrorCount
from greenlake_data_services.model.manufacturing_single import ManufacturingSingle
from greenlake_data_services.model.state import STATE
globals()['AdmitTime'] = AdmitTime
globals()['DiskAssociatedLinks'] = DiskAssociatedLinks
globals()['DiskCapacity'] = DiskCapacity
globals()['DiskLoop'] = DiskLoop
globals()['DiskPosition'] = DiskPosition
globals()['DiskPositionNow'] = DiskPositionNow
globals()['ErrorCount'] = ErrorCount
globals()['ManufacturingSingle'] = ManufacturingSingle
globals()['STATE'] = STATE
from greenlake_data_services.model.disk_details import DiskDetails


class TestDiskDetails(unittest.TestCase):
    """DiskDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiskDetails(self):
        """Test DiskDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DiskDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
