"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.clone_priority import ClonePriority
globals()['ClonePriority'] = ClonePriority
from greenlake_data_services.model.promote_clone_input import PromoteCloneInput


class TestPromoteCloneInput(unittest.TestCase):
    """PromoteCloneInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPromoteCloneInput(self):
        """Test PromoteCloneInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PromoteCloneInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
