"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.primera_application_set_details_replication_partner import PrimeraApplicationSetDetailsReplicationPartner


class TestPrimeraApplicationSetDetailsReplicationPartner(unittest.TestCase):
    """PrimeraApplicationSetDetailsReplicationPartner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrimeraApplicationSetDetailsReplicationPartner(self):
        """Test PrimeraApplicationSetDetailsReplicationPartner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PrimeraApplicationSetDetailsReplicationPartner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
