"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.led import LED
from greenlake_data_services.model.manufacturing_single import ManufacturingSingle
from greenlake_data_services.model.node_associated_links import NodeAssociatedLinks
from greenlake_data_services.model.state import STATE
from greenlake_data_services.model.uptime import Uptime
globals()['LED'] = LED
globals()['ManufacturingSingle'] = ManufacturingSingle
globals()['NodeAssociatedLinks'] = NodeAssociatedLinks
globals()['STATE'] = STATE
globals()['Uptime'] = Uptime
from greenlake_data_services.model.nodes_list import NodesList


class TestNodesList(unittest.TestCase):
    """NodesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodesList(self):
        """Test NodesList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodesList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
