"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.key_value import KeyValue
globals()['KeyValue'] = KeyValue
from greenlake_data_services.model.nimble_edit_snapshot_input import NimbleEditSnapshotInput


class TestNimbleEditSnapshotInput(unittest.TestCase):
    """NimbleEditSnapshotInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleEditSnapshotInput(self):
        """Test NimbleEditSnapshotInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleEditSnapshotInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
