"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.un_export_app_set_post import UnExportAppSetPost


class TestUnExportAppSetPost(unittest.TestCase):
    """UnExportAppSetPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnExportAppSetPost(self):
        """Test UnExportAppSetPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnExportAppSetPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
