"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.trusted_certificate_details_detail import TrustedCertificateDetailsDetail
from greenlake_data_services.model.trusted_certificate_details_enddate import TrustedCertificateDetailsEnddate
from greenlake_data_services.model.trusted_certificate_details_startdate import TrustedCertificateDetailsStartdate
globals()['TrustedCertificateDetailsDetail'] = TrustedCertificateDetailsDetail
globals()['TrustedCertificateDetailsEnddate'] = TrustedCertificateDetailsEnddate
globals()['TrustedCertificateDetailsStartdate'] = TrustedCertificateDetailsStartdate
from greenlake_data_services.model.trusted_certificates_list import TrustedCertificatesList


class TestTrustedCertificatesList(unittest.TestCase):
    """TrustedCertificatesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrustedCertificatesList(self):
        """Test TrustedCertificatesList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrustedCertificatesList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
