"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.vluns_list_initiators import VlunsListInitiators
from greenlake_data_services.model.vluns_list_single_port_pos import VlunsListSinglePortPos
from greenlake_data_services.model.vluns_list_state import VlunsListState
globals()['VlunsListInitiators'] = VlunsListInitiators
globals()['VlunsListSinglePortPos'] = VlunsListSinglePortPos
globals()['VlunsListState'] = VlunsListState
from greenlake_data_services.model.vluns_list_single import VlunsListSingle


class TestVlunsListSingle(unittest.TestCase):
    """VlunsListSingle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVlunsListSingle(self):
        """Test VlunsListSingle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VlunsListSingle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
