"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimble_fc_interface_list import NimbleFcInterfaceList
from greenlake_data_services.model.nimble_fc_port_list import NimbleFcPortList
globals()['NimbleFcInterfaceList'] = NimbleFcInterfaceList
globals()['NimbleFcPortList'] = NimbleFcPortList
from greenlake_data_services.model.nimble_controller_config import NimbleControllerConfig


class TestNimbleControllerConfig(unittest.TestCase):
    """NimbleControllerConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNimbleControllerConfig(self):
        """Test NimbleControllerConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NimbleControllerConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
