"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.nimblehistorical_metric_data import NimblehistoricalMetricData
globals()['NimblehistoricalMetricData'] = NimblehistoricalMetricData
from greenlake_data_services.model.storage_pool_performance_history import StoragePoolPerformanceHistory


class TestStoragePoolPerformanceHistory(unittest.TestCase):
    """StoragePoolPerformanceHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoragePoolPerformanceHistory(self):
        """Test StoragePoolPerformanceHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StoragePoolPerformanceHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
