"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import greenlake_data_services
from greenlake_data_services.model.replication_partner_list_policies import ReplicationPartnerListPolicies
from greenlake_data_services.model.sync_time import SyncTime
globals()['ReplicationPartnerListPolicies'] = ReplicationPartnerListPolicies
globals()['SyncTime'] = SyncTime
from greenlake_data_services.model.replication_partner_list import ReplicationPartnerList


class TestReplicationPartnerList(unittest.TestCase):
    """ReplicationPartnerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReplicationPartnerList(self):
        """Test ReplicationPartnerList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReplicationPartnerList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
