# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NimbleEditPoolInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'array_list': 'list[EditPoolNimbleArrayDetail]',
        'dedupe_all_volumes': 'bool',
        'dedupe_capable': 'bool',
        'description': 'str',
        'force': 'bool',
        'is_default': 'bool',
        'name': 'str'
    }

    attribute_map = {
        'array_list': 'array_list',
        'dedupe_all_volumes': 'dedupe_all_volumes',
        'dedupe_capable': 'dedupe_capable',
        'description': 'description',
        'force': 'force',
        'is_default': 'is_default',
        'name': 'name'
    }

    def __init__(self, array_list=None, dedupe_all_volumes=None, dedupe_capable=None, description=None, force=None, is_default=None, name=None):  # noqa: E501
        """NimbleEditPoolInput - a model defined in OpenAPI"""  # noqa: E501

        self._array_list = None
        self._dedupe_all_volumes = None
        self._dedupe_capable = None
        self._description = None
        self._force = None
        self._is_default = None
        self._name = None
        self.discriminator = None

        if array_list is not None:
            self.array_list = array_list
        if dedupe_all_volumes is not None:
            self.dedupe_all_volumes = dedupe_all_volumes
        if dedupe_capable is not None:
            self.dedupe_capable = dedupe_capable
        if description is not None:
            self.description = description
        if force is not None:
            self.force = force
        if is_default is not None:
            self.is_default = is_default
        if name is not None:
            self.name = name

    @property
    def array_list(self):
        """Gets the array_list of this NimbleEditPoolInput.  # noqa: E501

        List of arrays identified by their IDs, in the pool.  # noqa: E501

        :return: The array_list of this NimbleEditPoolInput.  # noqa: E501
        :rtype: list[EditPoolNimbleArrayDetail]
        """
        return self._array_list

    @array_list.setter
    def array_list(self, array_list):
        """Sets the array_list of this NimbleEditPoolInput.

        List of arrays identified by their IDs, in the pool.  # noqa: E501

        :param array_list: The array_list of this NimbleEditPoolInput.  # noqa: E501
        :type: list[EditPoolNimbleArrayDetail]
        """

        self._array_list = array_list

    @property
    def dedupe_all_volumes(self):
        """Gets the dedupe_all_volumes of this NimbleEditPoolInput.  # noqa: E501

        Indicates if dedupe is enabled by default for new volumes on this pool.  # noqa: E501

        :return: The dedupe_all_volumes of this NimbleEditPoolInput.  # noqa: E501
        :rtype: bool
        """
        return self._dedupe_all_volumes

    @dedupe_all_volumes.setter
    def dedupe_all_volumes(self, dedupe_all_volumes):
        """Sets the dedupe_all_volumes of this NimbleEditPoolInput.

        Indicates if dedupe is enabled by default for new volumes on this pool.  # noqa: E501

        :param dedupe_all_volumes: The dedupe_all_volumes of this NimbleEditPoolInput.  # noqa: E501
        :type: bool
        """

        self._dedupe_all_volumes = dedupe_all_volumes

    @property
    def dedupe_capable(self):
        """Gets the dedupe_capable of this NimbleEditPoolInput.  # noqa: E501

        Indicates whether the pool is capable of hosting deduped volumes.  # noqa: E501

        :return: The dedupe_capable of this NimbleEditPoolInput.  # noqa: E501
        :rtype: bool
        """
        return self._dedupe_capable

    @dedupe_capable.setter
    def dedupe_capable(self, dedupe_capable):
        """Sets the dedupe_capable of this NimbleEditPoolInput.

        Indicates whether the pool is capable of hosting deduped volumes.  # noqa: E501

        :param dedupe_capable: The dedupe_capable of this NimbleEditPoolInput.  # noqa: E501
        :type: bool
        """

        self._dedupe_capable = dedupe_capable

    @property
    def description(self):
        """Gets the description of this NimbleEditPoolInput.  # noqa: E501

        Text description of pool. String of up to 255 printable ASCII characters.  # noqa: E501

        :return: The description of this NimbleEditPoolInput.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NimbleEditPoolInput.

        Text description of pool. String of up to 255 printable ASCII characters.  # noqa: E501

        :param description: The description of this NimbleEditPoolInput.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def force(self):
        """Gets the force of this NimbleEditPoolInput.  # noqa: E501

        Forcibly delete the specified pool even if it contains deleted volumes whose space is being reclaimed. Forcibly remove an array from array_list via an update operation even if the array is not reachable. There should no volumes currently in the pool for the forced update operation to succeed.  # noqa: E501

        :return: The force of this NimbleEditPoolInput.  # noqa: E501
        :rtype: bool
        """
        return self._force

    @force.setter
    def force(self, force):
        """Sets the force of this NimbleEditPoolInput.

        Forcibly delete the specified pool even if it contains deleted volumes whose space is being reclaimed. Forcibly remove an array from array_list via an update operation even if the array is not reachable. There should no volumes currently in the pool for the forced update operation to succeed.  # noqa: E501

        :param force: The force of this NimbleEditPoolInput.  # noqa: E501
        :type: bool
        """

        self._force = force

    @property
    def is_default(self):
        """Gets the is_default of this NimbleEditPoolInput.  # noqa: E501

        Indicates if this is the default pool.  # noqa: E501

        :return: The is_default of this NimbleEditPoolInput.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this NimbleEditPoolInput.

        Indicates if this is the default pool.  # noqa: E501

        :param is_default: The is_default of this NimbleEditPoolInput.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def name(self):
        """Gets the name of this NimbleEditPoolInput.  # noqa: E501

        Name of pool. String of up to 64 alphanumeric characters, - and . and : are allowed after first character.  # noqa: E501

        :return: The name of this NimbleEditPoolInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NimbleEditPoolInput.

        Name of pool. String of up to 64 alphanumeric characters, - and . and : are allowed after first character.  # noqa: E501

        :param name: The name of this NimbleEditPoolInput.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NimbleEditPoolInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
