# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NimbleHealthStatusWithDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'associated_links': 'AssociatedLinks',
        'customer_id': 'str',
        'element_result': 'NimbleHCFResult',
        'generation': 'int',
        'on_demand': 'bool',
        'resource_uri': 'str'
    }

    attribute_map = {
        'associated_links': 'associatedLinks',
        'customer_id': 'customerId',
        'element_result': 'element_result',
        'generation': 'generation',
        'on_demand': 'on_demand',
        'resource_uri': 'resourceUri'
    }

    def __init__(self, associated_links=None, customer_id=None, element_result=None, generation=None, on_demand=None, resource_uri=None):  # noqa: E501
        """NimbleHealthStatusWithDetails - a model defined in OpenAPI"""  # noqa: E501

        self._associated_links = None
        self._customer_id = None
        self._element_result = None
        self._generation = None
        self._on_demand = None
        self._resource_uri = None
        self.discriminator = None

        if associated_links is not None:
            self.associated_links = associated_links
        if customer_id is not None:
            self.customer_id = customer_id
        if element_result is not None:
            self.element_result = element_result
        if generation is not None:
            self.generation = generation
        if on_demand is not None:
            self.on_demand = on_demand
        if resource_uri is not None:
            self.resource_uri = resource_uri

    @property
    def associated_links(self):
        """Gets the associated_links of this NimbleHealthStatusWithDetails.  # noqa: E501


        :return: The associated_links of this NimbleHealthStatusWithDetails.  # noqa: E501
        :rtype: AssociatedLinks
        """
        return self._associated_links

    @associated_links.setter
    def associated_links(self, associated_links):
        """Sets the associated_links of this NimbleHealthStatusWithDetails.


        :param associated_links: The associated_links of this NimbleHealthStatusWithDetails.  # noqa: E501
        :type: AssociatedLinks
        """

        self._associated_links = associated_links

    @property
    def customer_id(self):
        """Gets the customer_id of this NimbleHealthStatusWithDetails.  # noqa: E501

        customerId  # noqa: E501

        :return: The customer_id of this NimbleHealthStatusWithDetails.  # noqa: E501
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this NimbleHealthStatusWithDetails.

        customerId  # noqa: E501

        :param customer_id: The customer_id of this NimbleHealthStatusWithDetails.  # noqa: E501
        :type: str
        """

        self._customer_id = customer_id

    @property
    def element_result(self):
        """Gets the element_result of this NimbleHealthStatusWithDetails.  # noqa: E501


        :return: The element_result of this NimbleHealthStatusWithDetails.  # noqa: E501
        :rtype: NimbleHCFResult
        """
        return self._element_result

    @element_result.setter
    def element_result(self, element_result):
        """Sets the element_result of this NimbleHealthStatusWithDetails.


        :param element_result: The element_result of this NimbleHealthStatusWithDetails.  # noqa: E501
        :type: NimbleHCFResult
        """

        self._element_result = element_result

    @property
    def generation(self):
        """Gets the generation of this NimbleHealthStatusWithDetails.  # noqa: E501

        generation  # noqa: E501

        :return: The generation of this NimbleHealthStatusWithDetails.  # noqa: E501
        :rtype: int
        """
        return self._generation

    @generation.setter
    def generation(self, generation):
        """Sets the generation of this NimbleHealthStatusWithDetails.

        generation  # noqa: E501

        :param generation: The generation of this NimbleHealthStatusWithDetails.  # noqa: E501
        :type: int
        """

        self._generation = generation

    @property
    def on_demand(self):
        """Gets the on_demand of this NimbleHealthStatusWithDetails.  # noqa: E501

        Flag to indicate running the health checks and then report results.  # noqa: E501

        :return: The on_demand of this NimbleHealthStatusWithDetails.  # noqa: E501
        :rtype: bool
        """
        return self._on_demand

    @on_demand.setter
    def on_demand(self, on_demand):
        """Sets the on_demand of this NimbleHealthStatusWithDetails.

        Flag to indicate running the health checks and then report results.  # noqa: E501

        :param on_demand: The on_demand of this NimbleHealthStatusWithDetails.  # noqa: E501
        :type: bool
        """

        self._on_demand = on_demand

    @property
    def resource_uri(self):
        """Gets the resource_uri of this NimbleHealthStatusWithDetails.  # noqa: E501


        :return: The resource_uri of this NimbleHealthStatusWithDetails.  # noqa: E501
        :rtype: str
        """
        return self._resource_uri

    @resource_uri.setter
    def resource_uri(self, resource_uri):
        """Sets the resource_uri of this NimbleHealthStatusWithDetails.


        :param resource_uri: The resource_uri of this NimbleHealthStatusWithDetails.  # noqa: E501
        :type: str
        """

        self._resource_uri = resource_uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NimbleHealthStatusWithDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
