# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NimbleFcPortList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'bus_location': 'str',
        'name': 'str',
        'port': 'int',
        'slot': 'int'
    }

    attribute_map = {
        'bus_location': 'bus_location',
        'name': 'name',
        'port': 'port',
        'slot': 'slot'
    }

    def __init__(self, bus_location=None, name=None, port=None, slot=None):  # noqa: E501
        """NimbleFcPortList - a model defined in OpenAPI"""  # noqa: E501

        self._bus_location = None
        self._name = None
        self._port = None
        self._slot = None
        self.discriminator = None

        if bus_location is not None:
            self.bus_location = bus_location
        if name is not None:
            self.name = name
        if port is not None:
            self.port = port
        if slot is not None:
            self.slot = slot

    @property
    def bus_location(self):
        """Gets the bus_location of this NimbleFcPortList.  # noqa: E501

        Bus location for the fibre channel config.String of up to 64 alphanumeric characters  # noqa: E501

        :return: The bus_location of this NimbleFcPortList.  # noqa: E501
        :rtype: str
        """
        return self._bus_location

    @bus_location.setter
    def bus_location(self, bus_location):
        """Sets the bus_location of this NimbleFcPortList.

        Bus location for the fibre channel config.String of up to 64 alphanumeric characters  # noqa: E501

        :param bus_location: The bus_location of this NimbleFcPortList.  # noqa: E501
        :type: str
        """

        self._bus_location = bus_location

    @property
    def name(self):
        """Gets the name of this NimbleFcPortList.  # noqa: E501

        Name of the fibre channel config. String of up to 64 alphanumeric characters, - and . and : are allowed after first character.  # noqa: E501

        :return: The name of this NimbleFcPortList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NimbleFcPortList.

        Name of the fibre channel config. String of up to 64 alphanumeric characters, - and . and : are allowed after first character.  # noqa: E501

        :param name: The name of this NimbleFcPortList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def port(self):
        """Gets the port of this NimbleFcPortList.  # noqa: E501

        Port number for this fibre channel config.Unsigned 64-bit integer.  # noqa: E501

        :return: The port of this NimbleFcPortList.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this NimbleFcPortList.

        Port number for this fibre channel config.Unsigned 64-bit integer.  # noqa: E501

        :param port: The port of this NimbleFcPortList.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def slot(self):
        """Gets the slot of this NimbleFcPortList.  # noqa: E501

        Slot number for this fibre channel config. Unsigned 64-bit integer.  # noqa: E501

        :return: The slot of this NimbleFcPortList.  # noqa: E501
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """Sets the slot of this NimbleFcPortList.

        Slot number for this fibre channel config. Unsigned 64-bit integer.  # noqa: E501

        :param slot: The slot of this NimbleFcPortList.  # noqa: E501
        :type: int
        """

        self._slot = slot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NimbleFcPortList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
