# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NimbleSyslogdServerInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'syslog_port': 'int',
        'syslog_server': 'str'
    }

    attribute_map = {
        'syslog_port': 'syslog_port',
        'syslog_server': 'syslog_server'
    }

    def __init__(self, syslog_port=None, syslog_server=None):  # noqa: E501
        """NimbleSyslogdServerInfo - a model defined in OpenAPI"""  # noqa: E501

        self._syslog_port = None
        self._syslog_server = None
        self.discriminator = None

        if syslog_port is not None:
            self.syslog_port = syslog_port
        if syslog_server is not None:
            self.syslog_server = syslog_server

    @property
    def syslog_port(self):
        """Gets the syslog_port of this NimbleSyslogdServerInfo.  # noqa: E501

        Port number for syslogd server. Positive integer value up to 65535 representing TCP/IP port.  # noqa: E501

        :return: The syslog_port of this NimbleSyslogdServerInfo.  # noqa: E501
        :rtype: int
        """
        return self._syslog_port

    @syslog_port.setter
    def syslog_port(self, syslog_port):
        """Sets the syslog_port of this NimbleSyslogdServerInfo.

        Port number for syslogd server. Positive integer value up to 65535 representing TCP/IP port.  # noqa: E501

        :param syslog_port: The syslog_port of this NimbleSyslogdServerInfo.  # noqa: E501
        :type: int
        """

        self._syslog_port = syslog_port

    @property
    def syslog_server(self):
        """Gets the syslog_server of this NimbleSyslogdServerInfo.  # noqa: E501

        Hostname of the syslogd server. String of alphanumeric characters, valid range is from 2 to 255; Each label must be between 1 and 63 characters long; - and . are allowed after the first and before the last character.  # noqa: E501

        :return: The syslog_server of this NimbleSyslogdServerInfo.  # noqa: E501
        :rtype: str
        """
        return self._syslog_server

    @syslog_server.setter
    def syslog_server(self, syslog_server):
        """Sets the syslog_server of this NimbleSyslogdServerInfo.

        Hostname of the syslogd server. String of alphanumeric characters, valid range is from 2 to 255; Each label must be between 1 and 63 characters long; - and . are allowed after the first and before the last character.  # noqa: E501

        :param syslog_server: The syslog_server of this NimbleSyslogdServerInfo.  # noqa: E501
        :type: str
        """

        self._syslog_server = syslog_server

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NimbleSyslogdServerInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
