# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NodeCardList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'associated_links': 'list[AssociatedLinksInner]',
        'customer_id': 'str',
        'displayname': 'str',
        'domain': 'str',
        'fw_version': 'str',
        'generation': 'int',
        'id': 'str',
        'locate_enabled': 'bool',
        'manufacturing': 'ManufacturingSingle',
        'name': 'str',
        'node_card_type': 'str',
        'node_device_id': 'int',
        'node_id': 'str',
        'resource_uri': 'str',
        'revision': 'str',
        'safe_to_remove': 'bool',
        'service_led': 'LED',
        'slot': 'int',
        'system_id': 'str',
        'type': 'str'
    }

    attribute_map = {
        'associated_links': 'associatedLinks',
        'customer_id': 'customerId',
        'displayname': 'displayname',
        'domain': 'domain',
        'fw_version': 'fwVersion',
        'generation': 'generation',
        'id': 'id',
        'locate_enabled': 'locateEnabled',
        'manufacturing': 'manufacturing',
        'name': 'name',
        'node_card_type': 'nodeCardType',
        'node_device_id': 'nodeDeviceId',
        'node_id': 'nodeId',
        'resource_uri': 'resourceUri',
        'revision': 'revision',
        'safe_to_remove': 'safeToRemove',
        'service_led': 'serviceLED',
        'slot': 'slot',
        'system_id': 'systemId',
        'type': 'type'
    }

    def __init__(self, associated_links=None, customer_id=None, displayname=None, domain=None, fw_version=None, generation=None, id=None, locate_enabled=None, manufacturing=None, name=None, node_card_type=None, node_device_id=None, node_id=None, resource_uri=None, revision=None, safe_to_remove=None, service_led=None, slot=None, system_id=None, type=None):  # noqa: E501
        """NodeCardList - a model defined in OpenAPI"""  # noqa: E501

        self._associated_links = None
        self._customer_id = None
        self._displayname = None
        self._domain = None
        self._fw_version = None
        self._generation = None
        self._id = None
        self._locate_enabled = None
        self._manufacturing = None
        self._name = None
        self._node_card_type = None
        self._node_device_id = None
        self._node_id = None
        self._resource_uri = None
        self._revision = None
        self._safe_to_remove = None
        self._service_led = None
        self._slot = None
        self._system_id = None
        self._type = None
        self.discriminator = None

        if associated_links is not None:
            self.associated_links = associated_links
        if customer_id is not None:
            self.customer_id = customer_id
        if displayname is not None:
            self.displayname = displayname
        if domain is not None:
            self.domain = domain
        if fw_version is not None:
            self.fw_version = fw_version
        if generation is not None:
            self.generation = generation
        if id is not None:
            self.id = id
        if locate_enabled is not None:
            self.locate_enabled = locate_enabled
        if manufacturing is not None:
            self.manufacturing = manufacturing
        if name is not None:
            self.name = name
        if node_card_type is not None:
            self.node_card_type = node_card_type
        if node_device_id is not None:
            self.node_device_id = node_device_id
        if node_id is not None:
            self.node_id = node_id
        if resource_uri is not None:
            self.resource_uri = resource_uri
        if revision is not None:
            self.revision = revision
        if safe_to_remove is not None:
            self.safe_to_remove = safe_to_remove
        if service_led is not None:
            self.service_led = service_led
        if slot is not None:
            self.slot = slot
        if system_id is not None:
            self.system_id = system_id
        if type is not None:
            self.type = type

    @property
    def associated_links(self):
        """Gets the associated_links of this NodeCardList.  # noqa: E501

        Associated Links Details  # noqa: E501

        :return: The associated_links of this NodeCardList.  # noqa: E501
        :rtype: list[AssociatedLinksInner]
        """
        return self._associated_links

    @associated_links.setter
    def associated_links(self, associated_links):
        """Sets the associated_links of this NodeCardList.

        Associated Links Details  # noqa: E501

        :param associated_links: The associated_links of this NodeCardList.  # noqa: E501
        :type: list[AssociatedLinksInner]
        """

        self._associated_links = associated_links

    @property
    def customer_id(self):
        """Gets the customer_id of this NodeCardList.  # noqa: E501

        customerId  # noqa: E501

        :return: The customer_id of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this NodeCardList.

        customerId  # noqa: E501

        :param customer_id: The customer_id of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._customer_id = customer_id

    @property
    def displayname(self):
        """Gets the displayname of this NodeCardList.  # noqa: E501

        Name to be used for display purposes  # noqa: E501

        :return: The displayname of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._displayname

    @displayname.setter
    def displayname(self, displayname):
        """Sets the displayname of this NodeCardList.

        Name to be used for display purposes  # noqa: E501

        :param displayname: The displayname of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._displayname = displayname

    @property
    def domain(self):
        """Gets the domain of this NodeCardList.  # noqa: E501

        Domain that the resource belongs to  # noqa: E501

        :return: The domain of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this NodeCardList.

        Domain that the resource belongs to  # noqa: E501

        :param domain: The domain of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._domain = domain

    @property
    def fw_version(self):
        """Gets the fw_version of this NodeCardList.  # noqa: E501

        Firmware version  # noqa: E501

        :return: The fw_version of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._fw_version

    @fw_version.setter
    def fw_version(self, fw_version):
        """Sets the fw_version of this NodeCardList.

        Firmware version  # noqa: E501

        :param fw_version: The fw_version of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._fw_version = fw_version

    @property
    def generation(self):
        """Gets the generation of this NodeCardList.  # noqa: E501

        generation `Filter, Sort`  # noqa: E501

        :return: The generation of this NodeCardList.  # noqa: E501
        :rtype: int
        """
        return self._generation

    @generation.setter
    def generation(self, generation):
        """Sets the generation of this NodeCardList.

        generation `Filter, Sort`  # noqa: E501

        :param generation: The generation of this NodeCardList.  # noqa: E501
        :type: int
        """

        self._generation = generation

    @property
    def id(self):
        """Gets the id of this NodeCardList.  # noqa: E501

        Unique Identifier of the resource. `Filter`  # noqa: E501

        :return: The id of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NodeCardList.

        Unique Identifier of the resource. `Filter`  # noqa: E501

        :param id: The id of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def locate_enabled(self):
        """Gets the locate_enabled of this NodeCardList.  # noqa: E501

        Indicates if the locate beacon is enabled or not  # noqa: E501

        :return: The locate_enabled of this NodeCardList.  # noqa: E501
        :rtype: bool
        """
        return self._locate_enabled

    @locate_enabled.setter
    def locate_enabled(self, locate_enabled):
        """Sets the locate_enabled of this NodeCardList.

        Indicates if the locate beacon is enabled or not  # noqa: E501

        :param locate_enabled: The locate_enabled of this NodeCardList.  # noqa: E501
        :type: bool
        """

        self._locate_enabled = locate_enabled

    @property
    def manufacturing(self):
        """Gets the manufacturing of this NodeCardList.  # noqa: E501


        :return: The manufacturing of this NodeCardList.  # noqa: E501
        :rtype: ManufacturingSingle
        """
        return self._manufacturing

    @manufacturing.setter
    def manufacturing(self, manufacturing):
        """Sets the manufacturing of this NodeCardList.


        :param manufacturing: The manufacturing of this NodeCardList.  # noqa: E501
        :type: ManufacturingSingle
        """

        self._manufacturing = manufacturing

    @property
    def name(self):
        """Gets the name of this NodeCardList.  # noqa: E501

        Name of the resource.  # noqa: E501

        :return: The name of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NodeCardList.

        Name of the resource.  # noqa: E501

        :param name: The name of this NodeCardList.  # noqa: E501
        :type: str
        """
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501

        self._name = name

    @property
    def node_card_type(self):
        """Gets the node_card_type of this NodeCardList.  # noqa: E501

        Type of the node adapter card  # noqa: E501

        :return: The node_card_type of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._node_card_type

    @node_card_type.setter
    def node_card_type(self, node_card_type):
        """Sets the node_card_type of this NodeCardList.

        Type of the node adapter card  # noqa: E501

        :param node_card_type: The node_card_type of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._node_card_type = node_card_type

    @property
    def node_device_id(self):
        """Gets the node_device_id of this NodeCardList.  # noqa: E501

        ID of the node  # noqa: E501

        :return: The node_device_id of this NodeCardList.  # noqa: E501
        :rtype: int
        """
        return self._node_device_id

    @node_device_id.setter
    def node_device_id(self, node_device_id):
        """Sets the node_device_id of this NodeCardList.

        ID of the node  # noqa: E501

        :param node_device_id: The node_device_id of this NodeCardList.  # noqa: E501
        :type: int
        """

        self._node_device_id = node_device_id

    @property
    def node_id(self):
        """Gets the node_id of this NodeCardList.  # noqa: E501

        Unique Identifier of the node. `Filter, Sort`  # noqa: E501

        :return: The node_id of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this NodeCardList.

        Unique Identifier of the node. `Filter, Sort`  # noqa: E501

        :param node_id: The node_id of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def resource_uri(self):
        """Gets the resource_uri of this NodeCardList.  # noqa: E501

        resourceUri for detailed node card object  # noqa: E501

        :return: The resource_uri of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._resource_uri

    @resource_uri.setter
    def resource_uri(self, resource_uri):
        """Sets the resource_uri of this NodeCardList.

        resourceUri for detailed node card object  # noqa: E501

        :param resource_uri: The resource_uri of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._resource_uri = resource_uri

    @property
    def revision(self):
        """Gets the revision of this NodeCardList.  # noqa: E501

        Revision  # noqa: E501

        :return: The revision of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this NodeCardList.

        Revision  # noqa: E501

        :param revision: The revision of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._revision = revision

    @property
    def safe_to_remove(self):
        """Gets the safe_to_remove of this NodeCardList.  # noqa: E501

        Indicates if the component is safe to remove  # noqa: E501

        :return: The safe_to_remove of this NodeCardList.  # noqa: E501
        :rtype: bool
        """
        return self._safe_to_remove

    @safe_to_remove.setter
    def safe_to_remove(self, safe_to_remove):
        """Sets the safe_to_remove of this NodeCardList.

        Indicates if the component is safe to remove  # noqa: E501

        :param safe_to_remove: The safe_to_remove of this NodeCardList.  # noqa: E501
        :type: bool
        """

        self._safe_to_remove = safe_to_remove

    @property
    def service_led(self):
        """Gets the service_led of this NodeCardList.  # noqa: E501


        :return: The service_led of this NodeCardList.  # noqa: E501
        :rtype: LED
        """
        return self._service_led

    @service_led.setter
    def service_led(self, service_led):
        """Sets the service_led of this NodeCardList.


        :param service_led: The service_led of this NodeCardList.  # noqa: E501
        :type: LED
        """

        self._service_led = service_led

    @property
    def slot(self):
        """Gets the slot of this NodeCardList.  # noqa: E501

        Slot of the node adapter card  # noqa: E501

        :return: The slot of this NodeCardList.  # noqa: E501
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """Sets the slot of this NodeCardList.

        Slot of the node adapter card  # noqa: E501

        :param slot: The slot of this NodeCardList.  # noqa: E501
        :type: int
        """

        self._slot = slot

    @property
    def system_id(self):
        """Gets the system_id of this NodeCardList.  # noqa: E501

        systemId/Serial Number  of the array.  # noqa: E501

        :return: The system_id of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._system_id

    @system_id.setter
    def system_id(self, system_id):
        """Sets the system_id of this NodeCardList.

        systemId/Serial Number  of the array.  # noqa: E501

        :param system_id: The system_id of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._system_id = system_id

    @property
    def type(self):
        """Gets the type of this NodeCardList.  # noqa: E501

        type  # noqa: E501

        :return: The type of this NodeCardList.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NodeCardList.

        type  # noqa: E501

        :param type: The type of this NodeCardList.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeCardList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
