# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class QosPerformanceHistory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'qos_metrics_data': 'QosMetricsData',
        'request_uri': 'str'
    }

    attribute_map = {
        'qos_metrics_data': 'qosMetricsData',
        'request_uri': 'requestURI'
    }

    def __init__(self, qos_metrics_data=None, request_uri=None):  # noqa: E501
        """QosPerformanceHistory - a model defined in OpenAPI"""  # noqa: E501

        self._qos_metrics_data = None
        self._request_uri = None
        self.discriminator = None

        if qos_metrics_data is not None:
            self.qos_metrics_data = qos_metrics_data
        if request_uri is not None:
            self.request_uri = request_uri

    @property
    def qos_metrics_data(self):
        """Gets the qos_metrics_data of this QosPerformanceHistory.  # noqa: E501


        :return: The qos_metrics_data of this QosPerformanceHistory.  # noqa: E501
        :rtype: QosMetricsData
        """
        return self._qos_metrics_data

    @qos_metrics_data.setter
    def qos_metrics_data(self, qos_metrics_data):
        """Sets the qos_metrics_data of this QosPerformanceHistory.


        :param qos_metrics_data: The qos_metrics_data of this QosPerformanceHistory.  # noqa: E501
        :type: QosMetricsData
        """

        self._qos_metrics_data = qos_metrics_data

    @property
    def request_uri(self):
        """Gets the request_uri of this QosPerformanceHistory.  # noqa: E501

        requestUri for detailed storage object  # noqa: E501

        :return: The request_uri of this QosPerformanceHistory.  # noqa: E501
        :rtype: str
        """
        return self._request_uri

    @request_uri.setter
    def request_uri(self, request_uri):
        """Sets the request_uri of this QosPerformanceHistory.

        requestUri for detailed storage object  # noqa: E501

        :param request_uri: The request_uri of this QosPerformanceHistory.  # noqa: E501
        :type: str
        """

        self._request_uri = request_uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QosPerformanceHistory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
