# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class VolumePerformance(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'iops': 'KpiMetrics',
        'latency_ms': 'KpiMetrics',
        'request_uri': 'str',
        'resource_uri': 'str',
        'throughput_kbps': 'KpiMetrics'
    }

    attribute_map = {
        'iops': 'iops',
        'latency_ms': 'latencyMs',
        'request_uri': 'requestUri',
        'resource_uri': 'resourceUri',
        'throughput_kbps': 'throughputKbps'
    }

    def __init__(self, iops=None, latency_ms=None, request_uri=None, resource_uri=None, throughput_kbps=None):  # noqa: E501
        """VolumePerformance - a model defined in OpenAPI"""  # noqa: E501

        self._iops = None
        self._latency_ms = None
        self._request_uri = None
        self._resource_uri = None
        self._throughput_kbps = None
        self.discriminator = None

        if iops is not None:
            self.iops = iops
        if latency_ms is not None:
            self.latency_ms = latency_ms
        if request_uri is not None:
            self.request_uri = request_uri
        if resource_uri is not None:
            self.resource_uri = resource_uri
        if throughput_kbps is not None:
            self.throughput_kbps = throughput_kbps

    @property
    def iops(self):
        """Gets the iops of this VolumePerformance.  # noqa: E501


        :return: The iops of this VolumePerformance.  # noqa: E501
        :rtype: KpiMetrics
        """
        return self._iops

    @iops.setter
    def iops(self, iops):
        """Sets the iops of this VolumePerformance.


        :param iops: The iops of this VolumePerformance.  # noqa: E501
        :type: KpiMetrics
        """

        self._iops = iops

    @property
    def latency_ms(self):
        """Gets the latency_ms of this VolumePerformance.  # noqa: E501


        :return: The latency_ms of this VolumePerformance.  # noqa: E501
        :rtype: KpiMetrics
        """
        return self._latency_ms

    @latency_ms.setter
    def latency_ms(self, latency_ms):
        """Sets the latency_ms of this VolumePerformance.


        :param latency_ms: The latency_ms of this VolumePerformance.  # noqa: E501
        :type: KpiMetrics
        """

        self._latency_ms = latency_ms

    @property
    def request_uri(self):
        """Gets the request_uri of this VolumePerformance.  # noqa: E501

        requestUri for detailed volume object  # noqa: E501

        :return: The request_uri of this VolumePerformance.  # noqa: E501
        :rtype: str
        """
        return self._request_uri

    @request_uri.setter
    def request_uri(self, request_uri):
        """Sets the request_uri of this VolumePerformance.

        requestUri for detailed volume object  # noqa: E501

        :param request_uri: The request_uri of this VolumePerformance.  # noqa: E501
        :type: str
        """

        self._request_uri = request_uri

    @property
    def resource_uri(self):
        """Gets the resource_uri of this VolumePerformance.  # noqa: E501

        resourceUri for detailed volume object  # noqa: E501

        :return: The resource_uri of this VolumePerformance.  # noqa: E501
        :rtype: str
        """
        return self._resource_uri

    @resource_uri.setter
    def resource_uri(self, resource_uri):
        """Sets the resource_uri of this VolumePerformance.

        resourceUri for detailed volume object  # noqa: E501

        :param resource_uri: The resource_uri of this VolumePerformance.  # noqa: E501
        :type: str
        """

        self._resource_uri = resource_uri

    @property
    def throughput_kbps(self):
        """Gets the throughput_kbps of this VolumePerformance.  # noqa: E501


        :return: The throughput_kbps of this VolumePerformance.  # noqa: E501
        :rtype: KpiMetrics
        """
        return self._throughput_kbps

    @throughput_kbps.setter
    def throughput_kbps(self, throughput_kbps):
        """Sets the throughput_kbps of this VolumePerformance.


        :param throughput_kbps: The throughput_kbps of this VolumePerformance.  # noqa: E501
        :type: KpiMetrics
        """

        self._throughput_kbps = throughput_kbps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumePerformance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
